### ISSUE TITLE
[0.3.1] Suggested Changes

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#7]
Again, these are only offered as suggestions. Other testers with different playstyles may have differing opinions. In my opinion the Contained Ecosystems section is close to perfect, provides a great experience and needs no changes. Everything below relates to the Lunar Plane.

## 1. Power Usage of IF Laser Drills

The maximum rate that an IF Laser Drill consumes energy is 100 RF/tick. That's 400 RF/tick in total powering the Laser Base. At this rate it takes a little under 38 seconds to produce an ore, or about 11.5 minutes to produce all the ore to make the Blessed Portal Stone. I feel this amount of time is acceptable. 

However, any energy production above 400 RF/tick will not change the rate at which the Laser Base produces ores and is therefore un-needed at this stage. There is no incentive to make an IE Diesel Generator (4096 RF/tick) or run a Thermoelectric Generator off Liquid Blaze and Liquid Starlight (1500 RF/tick), or to move beyond LV Wire Connectors and Cables.

In my most recent playthrough I only used 4 IE Water Wheel banks, producing 82 x 4 = 328 RF/tick. It took about 15 minutes to make all of the required cobalt and ardite. A thermoelectric generator running on water and lava (easily semi-automatable) produces 300 RF/tick and would take only marginally longer.

**Suggestion:** Increase both the total RF needed and maximum RF input rate by a factor of 4 to 10. Then the player will have a choice between waiting significantly longer for cobalt and ardite, or increasing their power generation rate in return for shorter waiting times. In the latter case, better power transmission infrastructure will also be required.

To effect this change, in the laser_drill section (line 582) of industrialforegoing.cfg, multiply the values in the lines
        I:energyForWork=3000
and
	I:energyRate=100
by the required multiplication factor.

I used
        I:energyForWork=30000
and
	I:energyRate=1000
in testing. Feeding each Laser Drill with 1000 RF/tick produced an ore in just under 38 seconds, as expected.

## 2. Need to Obtain Resources from Lunar Plane Caves

The resources currently obtainable in the Cave System in the Lunar Planes are: Rock Crystal, Aquamarine, Glowstone and Iron Ore.

Due to various factors there is potentially little incentive to spend time in these beautiful-looking caves or to face their dangers. In my 0.3.1 playthrough I had no need to visit these caves to obtain resources. This may be different for someone who doesn't feel brave enough or prepared enough to tackle a Lunar Plane dungeon. I think this set of suggestions can be safely ignored if you are happy for tackling Lunar Planes Dungeons to mean there is little to no need to visit Lunar Planes Caves.

Iron Ore can be obtained in the Hexlands in large quantities as a byproduct of other mining. Aquamarine is plentiful on the surface in two structures, with little to no risk to obtain it. Glowstone is mostly needed for Illumination Powder, which is readily available in the bottom two floors of Lunar Plane Dungeons. Glowstone itself is also found in Astral Sorcery chests. Rock Crystal is only needed in small quantities, and sufficient can be obtained from the walls (behind pillars) of the lower levels of Dungeons, particularly with a Fortune III pickaxe.

**Suggestions:** 
- Remove (or greatly lower the amount) of Aquamarine Shale in surface structures. They would still be sources of Liquid Starlight and Sooty Marble. The main source of Aquamarine Shale would become caves.
- Remove glowstone from Astral Sorcery shrine chests.
- Add Glowstone to the Minerals and Ores chapter of the Lunar Plane part of the guide. Explain it spawns in caves.
- Remove Illumination Powder from Lunar Planes Dungeon chests. Possibly increase the frequency or quantity of diamonds as compensation.
- Add Sooty Marble to ore gen in the Lunar Plane at low y-levels (maybe 0 to 25 or so) at a similar frequency to Iron Ore. Remove the Sooty Marble recipe. Sooty Marble would then have three sources: surface structures in Dark Thickets, low level mining/caves in Lunar Plane and the floor of the bottom level of the Dungeon (large quantities).
- Add Sooty Marble to the Minerals and Ores chapter of the Lunar Plane part of the guide. Explain it spawns low down in caves or at the bottom of dungeons.

**Comment by xt9** [comment]
Changed the energy rate from 100 to 2048 so it scales up quite a bit, also changed energy required to 18000.

Will still need to take a look at point 2

**Comment by xt9** [comment]
**Suggestions:** 
- Remove (or greatly lower the amount) of Aquamarine Shale in surface structures. They would still be sources of Liquid Starlight and Sooty Marble. The main source of Aquamarine Shale would become caves.
Redid the dark shrine so it's a lot less aquamarine shale in it, also added Evoker spawners to the dark shrines to the can spawn in (a lot of them just despawned after the structure generated)

- Remove glowstone from Astral Sorcery shrine chests.
- Add Glowstone to the Minerals and Ores chapter of the Lunar Plane part of the guide. Explain it spawns in caves.
Can't really change this since you already get glowstone in Contained Ecosystems from sifting gold dust, you're already pretty much covered there, It's mostly for cave ambience, but I added a note about it in resources.


- Remove Illumination Powder from Lunar Planes Dungeon chests. Possibly increase the frequency or quantity of diamonds as compensation.
I don't see the need to change this right now but I might revisit it in the future.

- Add Sooty Marble to ore gen in the Lunar Plane at low y-levels (maybe 0 to 25 or so) at a similar frequency to Iron Ore. Remove the Sooty Marble recipe. Sooty Marble would then have three sources: surface structures in Dark Thickets, low level mining/caves in Lunar Plane and the floor of the bottom level of the Dungeon (large quantities).
- Add Sooty Marble to the Minerals and Ores chapter of the Lunar Plane part of the guide. Explain it spawns low down in caves or at the bottom of dungeons.
I feel like this is a good idea, I removed the recipes and added it to worldgen. also added Patchouli entries to cover this change.
